- name: Configure SSL on Apache Server
  hosts: apache
  tasks:

    - name: Rename and move SSL certificate
      command: cp /usr/local/apache2/conf/ssl/csr.crt /usr/local/apache2/conf/server.crt

    - name: Rename and move SSL key
      command: cp /usr/local/apache2/conf/ssl/csr.key /usr/local/apache2/conf/server.key

    - name: Update httpd-ssl.conf with SSL settings
      blockinfile:
        path: /usr/local/apache2/conf/extra/httpd-ssl.conf
        block: |
          ServerName 192.168.2.2
          <IfModule ssl_module>
            Listen 443
            SSLPassPhraseDialog  builtin
            SSLSessionCache       shmcb:/usr/local/apache2/logs/ssl_scache(512000)
            SSLSessionCacheTimeout  300
            SSLMutex  file:/usr/local/apache2/logs/ssl_mutex
            SSLCertificateFile "/usr/local/apache2/conf/server.crt"
            SSLCertificateKeyFile "/usr/local/apache2/conf/server.key"
            <VirtualHost _default_:443>
              ServerAdmin webmaster@localhost
              DocumentRoot "/usr/local/apache2/htdocs"
              ErrorLog "logs/ssl_error_log"
              CustomLog "logs/ssl_access_log" common
              SSLEngine on
            </VirtualHost>
          </IfModule>

    - name: Include httpd-ssl.conf in main configuration
      lineinfile:
        path: /usr/local/apache2/conf/httpd.conf
        line: Include conf/extra/httpd-ssl.conf
        insertafter: EOF

    - name: Load SSL and socache_shmcb modules
      lineinfile:
        path: /usr/local/apache2/conf/httpd.conf
        line: |
          LoadModule ssl_module modules/mod_ssl.so
          LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
        insertafter: EOF

    - name: Restart Apache to apply changes
      command: apachectl restart
      
