---
- name: Configure Router using cli_command
  hosts: router1
  gather_facts: no
  collections:
    - ansible.netcommon
  tasks:
    - name: Make sure the hostname is set up
      cli_command:
        command: |
          configure terminal
          hostname router2
          end

    - name: Configure the interface GigabitEthernet1
      cli_command:
        command: |
          configure terminal
          interface GigabitEthernet1
          ip address 192.168.56.108 255.255.255.0
          description Connected to LAN
          no shutdown
          end

    - name: Save configuration
      cli_command:
        command: write memory
