---
- name: Configure Router
  hosts: router1
  gather_facts: no
  tasks:
    - name: Make sure the hostname is set up
      shell: |
        hostname router2

    - name: Configure the interface GigabitEthernet1
      shell: |
        configure terminal
        interface GigabitEthernet1
        ip address 192.168.56.108 255.255.255.0
        description Connected to LAN
        no shutdown
        exit

    - name: Save configuration
      shell: |
        write memory
