---
- name: Configure Router
  hosts: router1
  gather_facts: no
  tasks:
    - name: Make sure the hostname is set up
      ios_command:
        commands:
          - configure terminal
          - hostname router2
          - end

    - name: Configure the interface GigabitEthernet1
      ios_command:
        commands:
          - configure terminal
          - interface GigabitEthernet1
          - ip address 192.168.56.108 255.255.255.0
          - description Connected to LAN
          - no shutdown
          - end

    - name: Save configuration
      ios_command:
        commands:
          - write memory
