- name: Configure Router
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios 
  tasks:
    - name: Make sure the hostname is set up
      ios_config:
        lines:
          - hostname router1

    - name: Configure the interface GigabitEthernet1
      ios_config:
        lines:
          - interface GigabitEthernet1
          - ip address 192.168.56.108 255.255.255.0
          - description Connected to LAN
          - no shutdown
        before:
          - interface GigabitEthernet1
        after:
          - exit

    - name: Configure the interface GigabitEthernet2
      ios_config:
        lines:
          - interface GigabitEthernet2
          - ip address 192.168.56.109 255.255.255.0
          - description Connected to LAN2
          - no shutdown
        before:
          - interface GigabitEthernet2
        after:
          - exit
    
    - name: Save configuration
      ios_command:
        commands:
          - write memory

