---
- name: Configure Router using shell
  hosts: all
  gather_facts: no
  tasks:
    - name: Make sure the hostname is set up
      ansible.builtin.shell: |
        enable
        configure terminal
        hostname router1
        end

    - name: Configure the interface GigabitEthernet1
      ansible.builtin.shell: |
        enable
        configure terminal
        interface GigabitEthernet1
        ip address 192.168.56.108 255.255.255.0
        description Connected to LAN
        no shutdown
        end

    - name: Save configuration
      ansible.builtin.shell: |
        enable
        write memory
