---
- name: Test connection to Cisco IOS Device
  hosts: csr1000v_router
  gather_facts: no
  tasks:
    - name: Test connectivity with ping
      ping:

    - name: Run a simple command to test connection
      raw: show version
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout_lines
